export interface Template {
  id: string
  name: string
  description: string
  language: string
  framework?: string
  price: number
  icon: string
  features: string[]
  useCase: string
  preview: string
}

export const templates: Template[] = [
  {
    id: 'react-admin-dashboard',
    name: 'React Admin Dashboard',
    description: 'Full-featured admin dashboard with CRUD operations, user management, and analytics',
    language: 'React',
    framework: 'Next.js + Shadcn/ui',
    price: 19,
    icon: '📊',
    features: [
      'Pre-built dashboard layout',
      'User management system',
      'Data tables with sorting',
      'Dark mode support',
      'Responsive design',
    ],
    useCase: 'Perfect for SaaS platforms, admin portals, and internal tools',
    preview: 'admin-dashboard-preview',
  },
  {
    id: 'fastapi-boilerplate',
    name: 'Python FastAPI Boilerplate',
    description: 'Production-ready FastAPI backend with authentication, database, and Docker',
    language: 'Python',
    framework: 'FastAPI',
    price: 14,
    icon: '🐍',
    features: [
      'JWT authentication',
      'SQLAlchemy ORM',
      'Docker setup',
      'Database migrations',
      'API documentation',
    ],
    useCase: 'Backend APIs, microservices, RESTful services',
    preview: 'fastapi-boilerplate-preview',
  },
  {
    id: 'vue3-ecommerce',
    name: 'Vue 3 + Tailwind E-Commerce Starter',
    description: 'Complete e-commerce template with product catalog, cart, and checkout flow',
    language: 'Vue',
    framework: 'Vue 3',
    price: 12,
    icon: '🛒',
    features: [
      'Product listing page',
      'Shopping cart system',
      'Product filters',
      'Responsive layout',
      'Payment integration ready',
    ],
    useCase: 'Online stores, product marketplaces, retail apps',
    preview: 'vue-ecommerce-preview',
  },
  {
    id: 'nextjs-saas-starter',
    name: 'Next.js SaaS Starter',
    description: 'Full-stack SaaS boilerplate with auth, payments, and database',
    language: 'React',
    framework: 'Next.js',
    price: 29,
    icon: '🚀',
    features: [
      'User authentication (Auth0/Firebase)',
      'Stripe integration',
      'Database schema',
      'Email notifications',
      'API routes',
      'Admin panel',
    ],
    useCase: 'SaaS applications, subscription services, multi-tenant platforms',
    preview: 'nextjs-saas-preview',
  },
  {
    id: 'nodejs-rest-api',
    name: 'Node.js REST API',
    description: 'Express-based REST API with validation, middleware, and testing setup',
    language: 'Node.js',
    framework: 'Express',
    price: 16,
    icon: '⚙️',
    features: [
      'Express server setup',
      'Input validation',
      'Error handling',
      'Jest testing framework',
      'Environment config',
      'CORS setup',
    ],
    useCase: 'RESTful APIs, backend services, microservices',
    preview: 'nodejs-rest-api-preview',
  },
  {
    id: 'react-native-starter',
    name: 'React Native Mobile Starter',
    description: 'Cross-platform mobile app template with Firebase integration',
    language: 'React Native',
    framework: 'React Native',
    price: 17,
    icon: '📱',
    features: [
      'Navigation setup',
      'Firebase auth',
      'Local storage',
      'Component library',
      'Push notifications ready',
    ],
    useCase: 'iOS/Android apps, mobile-first applications, cross-platform development',
    preview: 'react-native-starter-preview',
  },
  {
    id: 'graphql-server',
    name: 'GraphQL Server with Apollo',
    description: 'Production-ready GraphQL API with Apollo Server, MongoDB, and authentication',
    language: 'Node.js',
    framework: 'Apollo Server',
    price: 18,
    icon: '🔷',
    features: [
      'Apollo Server setup',
      'MongoDB integration',
      'JWT auth',
      'Query optimization',
      'Subscription support',
    ],
    useCase: 'GraphQL APIs, modern web services, real-time applications',
    preview: 'graphql-server-preview',
  },
  {
    id: 'tailwind-components',
    name: 'Tailwind Component Library',
    description: '50+ production-ready UI components built with Tailwind CSS',
    language: 'CSS',
    framework: 'Tailwind',
    price: 15,
    icon: '🎨',
    features: [
      '50+ components',
      'Dark mode variants',
      'Fully customizable',
      'Copy-paste ready',
      'Documentation included',
    ],
    useCase: 'UI libraries, design systems, rapid prototyping',
    preview: 'tailwind-components-preview',
  },
  {
    id: 'django-rest-framework',
    name: 'Django REST Framework',
    description: 'Full-stack Django API with DRF, PostgreSQL, and Docker',
    language: 'Python',
    framework: 'Django',
    price: 16,
    icon: '🟢',
    features: [
      'DRF setup',
      'PostgreSQL models',
      'Serializers',
      'Docker compose',
      'Testing suite',
    ],
    useCase: 'Django APIs, Python web services, enterprise backends',
    preview: 'django-rest-preview',
  },
  {
    id: 'typescript-monorepo',
    name: 'TypeScript Monorepo',
    description: 'Turborepo monorepo setup with shared packages, linting, and CI/CD',
    language: 'TypeScript',
    framework: 'Turborepo',
    price: 25,
    icon: '📦',
    features: [
      'Turborepo config',
      'Shared packages',
      'ESLint setup',
      'GitHub Actions CI/CD',
      'Workspace structure',
    ],
    useCase: 'Large projects, monorepos, multi-package applications',
    preview: 'typescript-monorepo-preview',
  },
]
